# Generated by Django 5.2.6 on 2025-10-05 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=64, null=True, unique=True, verbose_name='код активации'),
        ),
    ]
