# Generated by Django 5.2.6 on 2025-10-05 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='код активации'),
        ),
    ]
