# Generated by Django 5.2.6 on 2025-11-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price_per_hour',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('tutor', 'Репетитор')], db_index=True, max_length=10),
        ),
    ]
