# Generated by Django 5.2.6 on 2025-11-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_booking'),
        ('users', '0006_remove_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subject'),
        ),
    ]
