# Generated by Django 5.2.6 on 2025-11-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_booking_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=10),
        ),
    ]
