# Generated by Django 5.2.6 on 2025-11-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_booking_status'),
        ('users', '0006_remove_user_name_remove_user_surname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('missed', 'Пропущен')], db_index=True, default='scheduled', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('homework', models.TextField(blank=True, null=True)),
                ('student_rating', models.IntegerField(blank=True, null=True)),
                ('student_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='Из какой заявки создан урок (если создан из заявки)', on_delete=django.db.models.deletion.CASCADE, related_name='booking_lesson', to='lessons.booking')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='users.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['tutor', 'start_time'], name='lessons_les_tutor_i_f27c02_idx'), models.Index(fields=['student', 'start_time'], name='lessons_les_student_9253eb_idx')],
                'unique_together': {('tutor', 'start_time')},
            },
        ),
    ]
